[package]
name = "swc"
version = "0.5.1"
edition = "2021"
authors = ["Oliver Tale-Yazdi <oliver.tale-yazdi@parity.io>"]

[features]
polkadot = []

[dependencies]
swc_core = { version = "0.5.1", path = "../core" }

env_logger = "0.9.0"
log = "0.4.16"
clap = { version = "3.1.12", features = ["derive"] }
syn = { version = "1.0.91", features = ["parsing", "full"] }
ansi_term = "0.12.1"
comfy-table = { version = "5.0.1", default-features = false }

[dev-dependencies]
assert_cmd = "2.0.4"
serial_test = "*"
